### ISSUE TITLE
Suggester editor

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker#1021] opened 2020-06-29 14:52 UTC
Currently we have only available selectbox editor. For long lists would be nice to have suggester that will match value based on query `value like %pattern%` where pattern is part of value that was provided by user. At the begging filtering can be done on FE side.

We should use such editor for topic parameter in avro source/sink.

**Comment by dswiecki** [comment] 2021-06-22 09:44
Duplicate of #778

**Closed by dswiecki** 2021-06-22 09:44 UTC
Labels: development, enhancement
